/** URLs estáticas em /INICIO/galeria — fallback quando Drive não está acessível. */
export const GALLERY_STATIC_PHOTOS = {
  "autoridade-tributaria": [
    "/INICIO/galeria/autoridade-tributaria/A70A8666-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8668-1-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8668-1024x681.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8732-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8745-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8762-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8787-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8794-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8809-scaled.jpg",
    "/INICIO/galeria/autoridade-tributaria/A70A8826-scaled.jpg",
  ],
  "construcao-obras": [
    "/INICIO/galeria/construcao-obras/cover.jpg",
    "/INICIO/galeria/construcao-obras/quitunda-1.jpeg",
  ],
  mmec: [
    "/INICIO/galeria/mmec/MMEC-2025-1-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-11-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-13-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-14-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-15-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-16-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-17-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-18-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-2-2-1024x576.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-2-3-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-20-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-21-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-22-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-23-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-24-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-26-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-28-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-3-2-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-30-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-31-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-32-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-4-2-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-5-2-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-6-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-7-1-scaled.jpg",
    "/INICIO/galeria/mmec/MMEC-2025-9-1-scaled.jpg",
  ],
  gmt: [
    "/INICIO/galeria/gmt/GMT-2025-0-1-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-18-1-1-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-22-1-1-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-231-1-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-241-1-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-31-2-713x1024.jpg",
    "/INICIO/galeria/gmt/GMT-2025-31-3-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-34-2-scaled.jpg",
    "/INICIO/galeria/gmt/GMT-2025-41-2-scaled.jpg",
  ],
  agricultura: [
    "/INICIO/galeria/agricultura/Machambas1.jpg",
    "/INICIO/galeria/agricultura/Machambas13-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas14-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas17-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas2-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas21-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas23-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas25-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas27-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas32-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas35-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas37-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas41-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas47-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas48-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas5-copy-1-1024x530.jpg",
    "/INICIO/galeria/agricultura/Machambas51-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas55-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas57-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas59-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas72-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas76-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas79-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas80-scaled.jpg",
    "/INICIO/galeria/agricultura/Machambas81-scaled.jpg",
  ],
};

export function staticPhotosForSlug(slug) {
  const urls = GALLERY_STATIC_PHOTOS[slug] || [];
  return urls.map((url, index) => ({
    id: `static-${slug}-${index}`,
    name: url.split("/").pop() || `foto-${index + 1}.jpg`,
    url,
    thumbnailUrl: url,
    mimeType: "image/jpeg",
    source: "static",
  }));
}
